google/objax

.readthedocs.yml, objax/nn/layers.py
This file is needed to integrate readthedocs with github
=> Configuration for readthedocs

README.md, docs/source/advanced/gradients.rst, docs/source/advanced/jit.rst, docs/source/notebooks/Logistic_Regression.ipynb
mostly spelling typos, but one note re: what i feel is a tweak to make first example more readable.
=> fix some small doc errors

docs/source/advanced/variables_and_modules.rst, docs/source/objax/nn.rst, docs/source/objax/objax.rst
- Added see also in ModuleList to point to Sequential.
- Added code sample to Sequential.
- Clarified differentiability of TrainVar.assign.
=> Improvements to documentation (ModuleList, Sequential, TrainVar).

objax/functional/loss.py
Added mean_squared_error loss function
=> Add mean squared logarithmic loss function

docs/source/objax/functional.rst, tests/loss.py
1. Added Docs for Mean Absolute Error and Mean Squared Error
2. Added Tests for mae and mse
*  With default axis
*  With custom `keep_dims=[1]`
*  With no `keep_dims=[]`
=> Add docs and tests for mae, mse

objax/functional/loss.py, tests/loss.py
=> support >= 3d cross entropy with sparse labels

docs/source/objax/objax.rst, objax/gradient.py, tests/gradient.py
With reference to #40. Added a module `Grad`. `Grad` internally calls `GradValues` and return only the gradients.
* No linter error.
* All tests passed.
=> Add module Grad

docs/source/objax/nn.rst, objax/module.py, objax/nn/layers.py, objax/util/util.py, tests/sequential.py
- Support slicing to run part of the network.
- Support modules with arbitrary number of inputs/outputs.
=> Make objax.nn.Sequential more powerful.

docs/source/objax/objax.rst, objax/gradient.py, objax/module.py, objax/privacy/dpsgd/gradient.py, tests/gradient.py, tests/jit.py, tests/module.py, tests/parallel.py
- Signature support allows good integration with Python `inspect` module (as well as partial). Resolves #58 
- `Function` module is a convenience module to simplify the code for wrappers and can also be used for aesthetic reasons in general purpose user code.  Resolves #57
=> Add signature support to wrappers, add Function module.

objax/nn/layers.py, objax/typing.py, objax/util/util.py, tests/conv.py, tests/conv_transpose.py
=> Allow strings and numerical values for Conv2D/ConvTranspose2D padding.

objax/module.py, objax/util/util.py, tests/module.py, tests/util.py
=> Adding ForceArgs module

objax/optimizer/adam.py, tests/optimizer.py
@david-berthelot, #41 I've added changes to the Adam to override the default `beta1` and `beta2` parameters.
=> Override default beta params in Adam

docs/source/objax/nn.rst, objax/nn/init.py, tests/nn_init.py
I've implemented the identity initializer, used to train RNNs. 
Is there interest in this PR?
=> [Proposal] Identity Initializer

docs/source/objax/nn.rst, objax/nn/init.py, tests/nn_init.py
This PR implements the [orthogonal intialization](https://smerity.com/articles/2016/orthogonal_init.html), useful for training RNNs (and maybe general Neural Nets when combined with Orthogonal regularization)
Is there interest in this PR?
=> [Proposal] Orthogonal Initializer 

objax/functional/core/pooling.py, objax/nn/layers.py, tests/functional_pooling.py, tests/nn_init.py
=> Pooling padding.Resolves #91

CONTRIBUTING.md, README.md, docs/source/dev/adding_module.rst, docs/source/dev/setup.rst, docs/source/index.rst
=> Developer documentation and guide on adding new code

objax/_version.py
- Feature: Improved error messages.
- Feature: Extended syntax: allow assigning TrainVar without TrainRef for direction experimentation.
- Feature: Extended padding options or pad and convolution.
- Feature: Modified ResNet_V2 to be Keras compatible.
- Feature: Defaults can be overridden in __call__ for Adam, Momentum.
- BugFix: Layer norm initialization in GPT-2.
=> Release 1.2.0

docs/source/objax/nn.rst, objax/io/ops.py, objax/nn/layers.py, tests/sequential.py
Fixes #141, fixes #162 and fixes #163
=> Usability fixes, error messages and documentation.

objax/module.py, tests/parallel.py
=> Automatic broadcasting of scalars in Parallel.

docs/source/faq.rst, docs/source/index.rst
=> Initial version of FAQ

examples/image_classification/cifar10_advanced.py, examples/image_classification/cifar10_simple.py, objax/privacy/dpsgd/gradient.py, tests/gradient.py
- Add support to PrivateGradValues for extra return values after the loss.
- Bugfix in cifar10_simple.py where to pixel shift was not symmetric.
- Beautified output of cifar10_advanced.py.
=> Misc fixes batched together.

docs/source/tutorials.rst, examples/tutorials/objax_to_tf.ipynb
=> Objax to TF tutorial

objax/util/objax2tf.py
=> Remove tensorflow implicit dependency in jax2tf.

objax/_version.py
Fixes a dependency on tensorflow.
=> Release 1.3.1

docs/source/objax/objax.rst, docs/source/objax/util.rst, objax/module.py, objax/util/__init__.py, objax/util/tracing.py, tests/module.py, tests/tracing.py
This pull request implements https://github.com/google/objax/issues/197 and replaces another pull request https://github.com/google/objax/pull/198 which was a first draft of tracing.
=> Initial implementation of automatic variable tracing.

docs/source/advanced/gradients.rst, docs/source/advanced/variables_and_modules.rst, docs/source/faq.rst, docs/source/notebooks/Objax_Basics.ipynb, examples/tutorials/cifar10.ipynb, examples/tutorials/mnist-tutorial.ipynb
=> Update documentation to reflect that we don't need to use .value

objax/functional/core/activation.py, objax/functional/loss.py
=> I have added the swish function. Issue #225

examples/fixmatch/libml/zoo/convnet.py, examples/fixmatch/libml/zoo/resnet.py, objax/variable.py, objax/zoo/convnet.py, tests/loss.py, tests/objax2tf.py, tests/variable.py
=> Fix various test failures in Objax

.github/workflows/run_linter.yml, .github/workflows/run_tests.yml, docs/source/objax/objax.rst, objax/gradient.py, requirements.txt, setup.py, tests/gradient.py
Implements Jacobian and Hessian as requested in #234
=> Implementation of Jacobian and Hessian

examples/image_classification/imagenet_resnet50_train.py
Log training accuracy to monitor overfitting.
=> add training accuracy

objax/_version.py
=> Version 1.8
