docs/source/advanced/gradients.rst, docs/source/advanced/io.rst, docs/source/advanced/jit.rst, docs/source/advanced/variables_and_modules.rst, docs/source/notebooks/Custom_Networks.ipynb, docs/source/notebooks/Objax_Basics.ipynb
This looks like an awesome framework! I was following the documentation and noticed some typos that I fixed in this PR.
=> Fix typos in Sphinx documentation pages

examples/classify/semi_supervised/img/libml/augment/core.py
Cutout is supposed to remove a small area of an image. The current code keeps only the small area of the image. This PR inverts the area, to do the right thing.
=> Fix bug that inverts cutout crop area

examples/classify/semi_supervised/img/libml/augment/core.py, objax/module.py
If you try and run a parallel module over a batch of examples where the batch shape doesn't divide the number of devices, the code crashes in numpy land. Instead, throw a nicer error message.
=> Raise nicer error if parallel can't divide batch by num devices

docs/requirements.txt
sphinx-build that readthedocs uses is 1.8. The one we use locally is 3.2 and can create the documentation as we need it.
=> Attempt to fix https://github.com/google/objax/issues/72

docs/source/_static/objax.js, docs/source/objax/objax.rst
- Clarify Jit/Parallel use of variables for a module.
- Use JaxArray in docs (rather than its aliased value).
Fixes #78, resolves #79
=> Minor changes to documentation.

objax/module.py, objax/optimizer/momentum.py, tests/optimizer.py
@david-berthelot, With references to [this](https://github.com/google/objax/issues/41#issuecomment-703715128), I've added changes to the momentum module where we can override the default momentum value.
I'm facing `'The problem arose with the 'bool' function. '`  issue because of assigning `momentum = momentum or self.momentum` inside the `__call__`. I remember because of this I was doing `self.momentum = momentum`.
The detailed error log is mentioned below.
```python
self = <optimizer.TestOptimizers testMethod=test_square_momentum_override>
def test_square_momentum_override(self):
"""Test logistic loss for momentum optimizer."""
>       model_vars, loss = self._test_loss_opt('square', 'momentum', True)
tests/optimizer.py:140:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
=> Override default momentum

examples/gpt-2/gpt2.py
g should be initialized with ones and b with zeros. Looks like an accidental swap. Otherwise, this layer starts out outputting 1 instead of x.
=> Initialize layer-norm properly.

objax/nn/layers.py
If you pass a tensor with the wrong shape to conv, it gives this completely incomprehensible error message:
```
File "/home/ncarlini/.local/lib/python3.6/site-packages/jax/lax/lax.py", line 542, in conv_general_dilated
precision=_canonicalize_precision(precision))
File "/home/ncarlini/.local/lib/python3.6/site-packages/jax/core.py", line 202, in bind
out_tracer = top_trace.process_primitive(self, tracers, kwargs)
File "/home/ncarlini/.local/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 133, in process_primitive
return self.default_process_primitive(primitive, tracers, params)
File "/home/ncarlini/.local/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 141, in default_process_primitive
out_aval = primitive.abstract_eval(*avals, **params)
File …
```
=> Give better error when passing wrong input shape to convolution

objax/io/checkpoint.py
If you're not careful, sometimes you pass an incorrect path to the checkpoint directory.
By default, objax will create a new directory and then when you call .restore(), it will silently do nothing.
This PR makes objax warn the user that nothing is going to happen, so they have some hope at debugging what's going on. As with the other print() in the checkpoint class, it only prints if verbose is enabled.
=> Add warning message if restoring from empty path

tests/parallel.py
When testing #101 I noticed that three parallel tests fail on my machine. All of these are because the value computed is nearly, but not identical, to zero. This PR fixes that.
=> Fix parallel test cases to allow floats to be almost zero

README.md, docs/source/installation_setup.rst
Note: Starting from 0.1.56, jaxlib changed its naming scheme.
=> Updated instructions for installing jaxlib.

objax/io/ops.py
I always have a hard time with restore() and remembering if it's the model in memory that's wrong, or the checkpoint on disk that's wrong. This makes it very clear and says which is which.
=> Give a more specific error when loading variables aren't found

objax/io/checkpoint.py, objax/module.py
Currently if you forget to call `replicate()` on a `Parallel` module, it dies somewhere in JaX land in between the 5th and 6th circles of hell. This error makes it possible to understand what's going on and find your way back.
=> Give better error message when calling Parallel() without replicate()

objax/io/checkpoint.py
Currently if someone accidentally calls save or restore on a module, things crash with an unhelpful error. This gives a better error.
=> Give error if passing the wrong type (e.g., a module) to checkpoint save or restore

objax/module.py, tests/parallel.py
The default is True to preserve the behavior of splitting the batch
dimension across devices.
If False, arguments are passed directly to jax.pmap without reshaping.
This supports cases, for example, where an argument is a list of tensors
to be split across devices.
=> Add support on objax.Parallel for list arguments.

objax/gradient.py, objax/io/checkpoint.py
Currently `input_argnums` expects a tuple. If you pass the integer 0, then the `or` treats this as if you passed nothing, and so  it passes an empty tuple and silently does the wrong thing. This fixes that to check the type.
=> Add better error to objax.GradValues function for input_argnums

objax/gradient.py, objax/module.py, objax/nn/layers.py, objax/optimizer/adam.py, objax/optimizer/ema.py, objax/optimizer/lars.py, objax/optimizer/momentum.py, objax/optimizer/sgd.py, objax/privacy/dpsgd/gradient.py, objax/random/random.py, objax/util/util.py, objax/variable.py, tests/repr.py
See sample below:
```python
import functools
import objax
m = objax.nn.Sequential([
objax.nn.Linear(2, 3),
objax.functional.leaky_relu,
objax.nn.Sequential([
functools.partial(objax.functional.leaky_relu, negative_slope=0.5),
objax.nn.Linear(4, 5)]),
objax.functional.tanh,
objax.nn.MovingAverage((2, 3), 4, 0.2),
objax.nn.ExponentialMovingAverage((5, 6)),
objax.nn.BatchNorm((3, 4, 5), (1, 7)),
objax.nn.BatchNorm0D(8),
objax.nn.BatchNorm1D(9),
objax.nn.BatchNorm2D(19),
objax.nn.Conv2D(4, 5, k=3),
objax.nn.ConvTranspose2D(4, 5, k=3),
objax.nn.Dropout(0.7),
objax.nn.SyncedBatchNorm((3, 4, 5), (1, 7)),
objax.nn.SyncedBatchNorm0D(8),
objax.nn.SyncedBatchNorm1D(9),
objax.nn.SyncedBatchNorm2D(19),
])
print(m)
```
Output:
```plain
objax.nn.Sequential(
[0] objax.nn.Linear(nin=2, nout=3, …
```
=> Adding support for __repr__, fixes #142

objax/zoo/resnet_v2.py, tests/resnet_v2.py
This is necessary because some versions of Tensorflow perform lazy
loading of modules, thus tf.keras.applications.__dict__ may not work
as expected.
=> Change the way to access tf.keras.applications

objax/privacy/dpsgd/gradient.py, tests/gradient.py
This PR implements a two-phase algorithm for per-sample gradient clipping with the goal of improving memory efficiency for the training of private deep models. The two steps are: (1) accumulate the norms of the gradient per sample and (2) use those norm values to perform a weighted backward pass that is equivalent to per-sample clipping. The user can choose whether to use this new algorithm or the currently implemented one through a boolean argument.
The unit-tests have been adapted to check results for both algorithms.
Let me know if this fits well!
=> Implementing 2 phases DP-SGD

objax/io/ops.py, objax/nn/layers.py, objax/optimizer/ema.py, objax/variable.py, requirements.txt, tests/jit.py, tests/variable.py
This is a prototype implementation of https://github.com/google/objax/issues/111
This is reasonably well tested and complete implementation of JAX duck typing, which allows to use Objax variables in mathematical expressions without explicitly calling `.value`.
This change does not include documentation, updates of examples, etc... which will be done in future pull requests.
=> Objax variables could be used in place of native JAX arrays

objax/functional/loss.py
Related to Issue #190. I have included warning checkpoints only to those functions that doesn't raise error by default in order to avoid unnecessary warnings.
=> Raised WARNINGS if input arguments dont have same shape 

README.md
The existing instructions are out of date (prompted by https://stackoverflow.com/q/73472417).
=> README: fix jaxlib GPU installation instructions

docs/source/notebooks/Objax_Basics.ipynb
See https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-2-march-16-2022
The functions `jax.ops.index_update`, `jax.ops.index_add`, which were deprecated in 0.2.22, have been removed.
=> Fix jax index update in the tutorial
